algoritmo "semnome"
// Função :
// Autor :
// Data : 18/11/2022
// Seção de Declarações 

var
   nota1, nota2, media: real

inicio
// Seção de Comandos 
   escreva("Digite a nota 1: ")  // 6.0   3.0   5.0   3.5   4.5   8.0   8.0
   leia(nota1)

   escreva("Digite a nota 2: ")  // 8.0   2.5   4.0   6.5   4.0   6.0   9.0
   leia(nota2)
   
   media <- (nota1 * 0.4) + (nota2 * 0.6)
   
   escreva("Sua media eh: ", media)  //  7.2    2.7   4.4   5.3   4.2   8.6

fimalgoritmo
